services:
#    sensio_customer_id.example:
#        class: Sensio\CustomerIdBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    prefix.listener:
        class: Sensio\CustomerIdBundle\Prefix\Listener
        arguments:
            - @router
        tags:
            - { name: kernel.event_listener, event: kernel.request }
